name: Test

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.3.0'  # Replace with the version of Node.js you are using

      - name: Install dependencies
        run: npm install

      - name: Run tests with Jest
        run: npm test  # Replace with your test script command  

  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '19.3.0'  # Replace with the version of Node.js you are using

      - name: Create and configure .npmrc
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          OWNER: ${{ github.repository_owner }}  # Retrieve repository owner dynamically
        run: |
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          echo "@${OWNER}:registry=https://npm.pkg.github.com/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${NPM_AUTH_TOKEN}" >> ~/.npmrc

      - name: Install dependencies
        run: npm install

      - name: Build library with Rollup
        run: npm run rollup 

      - name: Publish to npm
        run: npm publish --access public